export const LEARNING_SCHEDULE_OPTIONS = [
	{ name: '929', value: '929' },
	{ name: 'Arukh HaShulchan Yomi', value: 'arukhhashulchanyomi' },
	{ name: 'Chofetz Chaim', value: 'chofetzchaim' },
	{ name: "Daf HaYomi B'Halacha (Dirshu)", value: 'dirshudafhalacha' },
	{ name: 'Daf Weekly', value: 'dafweekly' },
	{ name: 'Daf Weekly Sunday', value: 'dafweeklysunday' },
	{ name: 'Daf Yomi', value: 'dafyomi' },
	{ name: 'Dirshu Amud Yomi', value: 'dirshuamudyomi' },
	{ name: 'Kitzur Shulchan Aruch Yomi', value: 'kitzurshulchanaruch' },
	{ name: 'Mishna Yomi', value: 'mishnayomi' },
	{ name: 'Nach Yomi', value: 'nachyomi' },
	{ name: 'Perek Yomi', value: 'perekyomi' },
	{ name: 'Pirkei Avot (Summer)', value: 'pirkeiavotsummer' },
	{ name: 'Psalms', value: 'psalms' },
	{ name: 'Rambam 1 Chapter', value: 'rambam1' },
	{ name: 'Rambam 3 Chapters', value: 'rambam3' },
	{ name: 'Sefer HaMitzvot', value: 'seferhamitzvot' },
	{ name: 'Shemirat HaLashon', value: 'shemirathalashon' },
	{ name: 'Tanakh Yomi', value: 'tanakhyomi' },
	{ name: 'Yerushalmi Yomi (Schottenstein)', value: 'yerushalmi-schottenstein' },
	{ name: 'Yerushalmi Yomi (Vilna)', value: 'yerushalmi-vilna' },
];
